#ifndef EVENTBUS_VISIBILITY_H
#define EVENTBUS_VISIBILITY_H

#include "dexode/config.h"

#ifndef EVENTBUS_BUILD_STATIC
#if defined(EVENTBUS_EXPORTS)
#define EVENTBUS_EXPORT EVENTBUS_VISIBILITY_EXPORT
#else
#define EVENTBUS_EXPORT EVENTBUS_VISIBILITY_IMPORT
#endif
#else
#define EVENTBUS_EXPORT EVENTBUS_VISIBILITY_STATIC
#endif
#define EVENTBUS_LOCAL EVENTBUS_VISIBILITY_LOCAL

#endif //EVENTBUS_VISIBILITY_H